export const paletteVars = {
  brand: {
    orange: "var(--brand-orange)",
    orangeStrong: "var(--brand-orange-strong)",
    blue: "var(--brand-blue)",
    blueStrong: "var(--brand-blue-strong)",
    indigo: "var(--brand-indigo)",
    indigoStrong: "var(--brand-indigo-strong)",
  },
  neutral: {
    background: "var(--background)",
    foreground: "var(--foreground)",
    surface: "var(--surface)",
    surfaceSoft: "var(--surface-soft)",
    surfaceAlt: "var(--surface-alt)",
    line: "var(--line)",
    lineStrong: "var(--line-strong)",
    muted: "var(--ink-muted)",
    mutedSoft: "var(--ink-soft)",
    body: "var(--ink-body)",
    footer: "var(--footer-bg)",
  },
  tones: {
    sky: {
      soft: "var(--tone-sky-soft)",
      pale: "var(--tone-sky-pale)",
      base: "var(--tone-sky-base)",
      deep: "var(--tone-sky-deep)",
    },
    orange: {
      soft: "var(--tone-orange-soft)",
      pale: "var(--tone-orange-pale)",
      base: "var(--tone-orange-base)",
      deep: "var(--tone-orange-deep)",
    },
    teal: {
      soft: "var(--tone-teal-soft)",
      base: "var(--tone-teal-base)",
      deep: "var(--tone-teal-deep)",
    },
    indigo: {
      soft: "var(--tone-indigo-soft)",
      base: "var(--tone-indigo-base)",
      deep: "var(--tone-indigo-deep)",
    },
    green: {
      soft: "var(--tone-green-soft)",
      base: "var(--tone-green-base)",
      deep: "var(--tone-green-deep)",
    },
    purple: {
      soft: "var(--tone-purple-soft)",
      base: "var(--tone-purple-base)",
      deep: "var(--tone-purple-deep)",
    },
    amber: {
      soft: "var(--tone-amber-soft)",
      base: "var(--tone-amber-base)",
      deep: "var(--tone-amber-deep)",
    },
    red: {
      soft: "var(--tone-red-soft)",
      base: "var(--tone-red-base)",
      deep: "var(--tone-red-deep)",
    },
    pink: {
      soft: "var(--tone-pink-soft)",
      base: "var(--tone-pink-base)",
      deep: "var(--tone-pink-deep)",
    },
  },
  shadows: {
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    surfaceSoft: "var(--shadow-surface-soft)",
    panelSoft: "var(--shadow-panel-soft)",
    surfaceWarm: "var(--shadow-surface-warm)",
    panelElevated: "var(--shadow-panel-elevated)",
    panelStrong: "var(--shadow-panel-strong)",
    brandVioletMd: "var(--shadow-brand-violet-md)",
    brandVioletLg: "var(--shadow-brand-violet-lg)",
    brandOrangeSm: "var(--shadow-brand-orange-sm)",
    brandOrangeMd: "var(--shadow-brand-orange-md)",
    brandOrangeLgSoft: "var(--shadow-brand-orange-lg-soft)",
    brandOrangeLg: "var(--shadow-brand-orange-lg)",
    brandBlueMd: "var(--shadow-brand-blue-md)",
    menu: "var(--shadow-menu)",
    cardHover: "var(--shadow-card-hover)",
    stepBase: "var(--shadow-step-base)",
    stepHover: "var(--shadow-step-hover)",
  },
} as const;
