import type { Booking } from "@/lib/types";

import { clients } from "@/lib/mock-data/clients";
import { services } from "@/lib/mock-data/services";
import { talents } from "@/lib/mock-data/talents";

export const bookings: Booking[] = [
  {
    id: "b1",
    serviceId: "s1",
    service: services[0],
    clientId: "c1",
    client: clients[0],
    talentId: "t1",
    talent: talents[0],
    projectDetails: "We need a complete redesign of our startup's website. Looking for a modern, clean interface that highlights our tech products. Target audience is B2B professionals.",
    budget: 4000,
    notes: "Please use our existing brand colors (blue and white). We'd like the project done within 3 weeks.",
    status: "pending",
    createdAt: "2024-11-01T00:00:00Z",
    updatedAt: "2024-11-05T00:00:00Z",
  },
  {
    id: "b2",
    serviceId: "s7",
    service: services[6],
    clientId: "c2",
    client: clients[1],
    talentId: "t5",
    talent: talents[4],
    projectDetails: "Need a complete brand identity for our café. We want something warm, inviting, and distinctly Bicolano. The logo should incorporate local elements.",
    budget: 4500,
    status: "pending",
    createdAt: "2024-11-10T00:00:00Z",
    updatedAt: "2024-11-10T00:00:00Z",
  },
  {
    id: "b3",
    serviceId: "s3",
    service: services[2],
    clientId: "c1",
    client: clients[0],
    talentId: "t2",
    talent: talents[1],
    projectDetails: "Build a portfolio website for our startup hub to showcase member startups and their products. Should be fast, responsive, and SEO-friendly.",
    budget: 10000,
    status: "completed",
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-10-20T00:00:00Z",
  },
  {
    id: "b4",
    serviceId: "s6",
    service: services[5],
    clientId: "c2",
    client: clients[1],
    talentId: "t4",
    talent: talents[3],
    projectDetails: "Edit 5 promotional videos for our café's social media. Each video should be 30-60 seconds with upbeat music and text overlays showing our menu items.",
    budget: 2500,
    status: "accepted",
    createdAt: "2024-11-12T00:00:00Z",
    updatedAt: "2024-11-13T00:00:00Z",
  },
  {
    id: "b5",
    serviceId: "s9",
    service: services[8],
    clientId: "c1",
    client: clients[0],
    talentId: "t6",
    talent: talents[5],
    projectDetails: "Photograph our upcoming startup pitch event. Need both candid shots and professional headshots of speakers and attendees.",
    status: "pending",
    createdAt: "2024-11-14T00:00:00Z",
    updatedAt: "2024-11-14T00:00:00Z",
  },
];
