import type { ServiceListing } from "@/lib/types";

export const services: ServiceListing[] = [
  {
    id: "s1",
    talentId: "t1",
    title: "Complete UI/UX Design Package",
    description: "End-to-end UI/UX design including user research, wireframing, high-fidelity mockups, and interactive prototypes. Includes up to 10 screens and 2 revision rounds.",
    category: "ui-ux-design",
    price: 3500,
    status: "published",
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "s2",
    talentId: "t1",
    title: "Mobile App Design",
    description: "Design beautiful and functional mobile app interfaces for iOS or Android. Includes wireframes, UI design, and a clickable prototype.",
    category: "ui-ux-design",
    price: 5000,
    status: "published",
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-09-15T00:00:00Z",
  },
  {
    id: "s3",
    talentId: "t2",
    title: "Custom Website Development",
    description: "Full-stack website development with React/Next.js. Includes responsive design, SEO, and deployment. Perfect for portfolios, blogs, or landing pages.",
    category: "web-development",
    price: 8000,
    status: "published",
    createdAt: "2024-08-10T00:00:00Z",
    updatedAt: "2024-08-10T00:00:00Z",
  },
  {
    id: "s4",
    talentId: "t2",
    title: "E-Commerce Store Setup",
    description: "Complete e-commerce store built with modern technologies. Includes product catalog, shopping cart, checkout flow, and admin panel.",
    category: "web-development",
    price: 15000,
    status: "published",
    createdAt: "2024-08-20T00:00:00Z",
    updatedAt: "2024-08-20T00:00:00Z",
  },
  {
    id: "s5",
    talentId: "t3",
    title: "SEO Blog Content Package",
    description: "5 SEO-optimized blog posts (1000-1500 words each) with keyword research, meta descriptions, and internal linking strategy.",
    category: "content-writing",
    price: 2500,
    status: "published",
    createdAt: "2024-10-01T00:00:00Z",
    updatedAt: "2024-10-01T00:00:00Z",
  },
  {
    id: "s6",
    talentId: "t4",
    title: "Short-Form Video Editing",
    description: "Professional editing for Reels, TikTok, or YouTube Shorts. Includes cuts, transitions, text overlays, music sync, and color correction. Up to 5 videos.",
    category: "video-editing",
    price: 2000,
    status: "published",
    createdAt: "2024-09-10T00:00:00Z",
    updatedAt: "2024-09-10T00:00:00Z",
  },
  {
    id: "s7",
    talentId: "t5",
    title: "Brand Identity Package",
    description: "Complete brand identity including logo design (3 concepts), color palette, typography guide, and brand guidelines document.",
    category: "graphic-design",
    price: 4000,
    status: "published",
    createdAt: "2024-07-15T00:00:00Z",
    updatedAt: "2024-07-15T00:00:00Z",
  },
  {
    id: "s8",
    talentId: "t5",
    title: "Social Media Graphics Set",
    description: "10 custom social media graphics for Instagram, Facebook, or Twitter. Includes templates you can reuse and edit in Canva.",
    category: "graphic-design",
    price: 1500,
    status: "published",
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2024-08-01T00:00:00Z",
  },
  {
    id: "s9",
    talentId: "t6",
    title: "Event Photography Package",
    description: "Professional event photography (up to 4 hours). Includes 100+ edited photos delivered within 5 business days.",
    category: "photography",
    price: 5000,
    status: "published",
    createdAt: "2024-06-20T00:00:00Z",
    updatedAt: "2024-06-20T00:00:00Z",
  },
  {
    id: "s10",
    talentId: "t6",
    title: "Product Photography",
    description: "Studio-quality product photos (up to 10 products). Includes white background shots and lifestyle shots.",
    category: "photography",
    price: 3000,
    status: "published",
    createdAt: "2024-07-01T00:00:00Z",
    updatedAt: "2024-07-01T00:00:00Z",
  },
  {
    id: "s11",
    talentId: "t1",
    title: "Landing Page Wireframe",
    description: "Quick wireframe and low-fidelity prototype for a single landing page. Great for validating ideas before full design.",
    category: "ui-ux-design",
    price: 1000,
    status: "draft",
    createdAt: "2024-10-10T00:00:00Z",
    updatedAt: "2024-10-10T00:00:00Z",
  },
];
