import type { TalentProfile } from "@/lib/types";

export const talents: TalentProfile[] = [
  {
    id: "t1",
    userId: "u1",
    username: "maria-santos",
    firstName: "Maria",
    lastName: "Santos",
    email: "maria.santos@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_maria.png",
    initials: "MS",
    bio: "Passionate UI/UX designer with 3+ years of experience creating intuitive digital experiences. I specialize in mobile-first design and accessible interfaces. Currently pursuing a degree in Information Technology at Bicol University.",
    role: "talent",
    headline: "UI/UX Designer & Prototyping Specialist",
    location: "Legazpi City",
    minRate: 500,
    maxRate: 800,
    skills: [
      { name: "Figma", level: "expert" },
      { name: "Adobe XD", level: "expert" },
      { name: "Prototyping", level: "expert" },
      { name: "User Research", level: "intermediate" },
      { name: "Wireframing", level: "expert" },
      { name: "Design Systems", level: "intermediate" },
    ],
    rating: 4.9,
    reviewCount: 87,
    available: true,
    servicesCount: 3,
    completedProjects: 42,
    verified: true,
    phone: "+63 917 123 4567",
    socials: { facebook: "maria.santos.bu", instagram: "@maria.designs" },
    createdAt: "2024-08-15T00:00:00Z",
  },
  {
    id: "t2",
    userId: "u2",
    username: "john-reyes",
    firstName: "John",
    lastName: "Reyes",
    email: "john.reyes@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_john.png",
    initials: "JR",
    bio: "Full-stack developer specializing in React, Next.js, and Node.js. I love building performant and scalable web applications. Dean's List awardee at Bicol University's College of Science.",
    role: "talent",
    headline: "Full Stack Developer",
    location: "Daraga",
    minRate: 800,
    maxRate: 1200,
    skills: [
      { name: "React", level: "expert" },
      { name: "Next.js", level: "expert" },
      { name: "Node.js", level: "expert" },
      { name: "TypeScript", level: "expert" },
      { name: "MongoDB", level: "intermediate" },
      { name: "Tailwind CSS", level: "expert" },
    ],
    rating: 5,
    reviewCount: 124,
    available: true,
    servicesCount: 4,
    completedProjects: 68,
    verified: true,
    phone: "+63 918 234 5678",
    socials: { facebook: "john.reyes.dev", instagram: "@john.codes" },
    createdAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "t3",
    userId: "u3",
    username: "ana-cruz",
    firstName: "Ana",
    lastName: "Cruz",
    email: "ana.cruz@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_ana.png",
    initials: "AC",
    bio: "Creative content writer and SEO specialist. I craft engaging blog posts, website copy, and marketing materials that connect with audiences. Journalism major at Bicol University.",
    role: "talent",
    headline: "Content Writer & SEO Specialist",
    location: "Legazpi City",
    minRate: 400,
    maxRate: 600,
    skills: [
      { name: "SEO Writing", level: "expert" },
      { name: "Copywriting", level: "expert" },
      { name: "Blog Posts", level: "expert" },
      { name: "Social Media Copy", level: "intermediate" },
      { name: "Technical Writing", level: "intermediate" },
    ],
    rating: 4.8,
    reviewCount: 65,
    available: false,
    servicesCount: 2,
    completedProjects: 35,
    verified: true,
    phone: "+63 919 345 6789",
    socials: { facebook: "ana.cruz.writes", instagram: "@ana.writesstuff" },
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "t4",
    userId: "u4",
    username: "carlos-mendoza",
    firstName: "Carlos",
    lastName: "Mendoza",
    email: "carlos.mendoza@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_carlos.png",
    initials: "CM",
    bio: "Award-winning video editor with expertise in Adobe Premiere Pro and After Effects. I create compelling visual stories for brands, events, and social media. Film & Media Arts student at Bicol University.",
    role: "talent",
    headline: "Video Editor & Motion Designer",
    location: "Tabaco City",
    minRate: 600,
    maxRate: 900,
    skills: [
      { name: "Premiere Pro", level: "expert" },
      { name: "After Effects", level: "expert" },
      { name: "Color Grading", level: "expert" },
      { name: "Motion Graphics", level: "intermediate" },
      { name: "DaVinci Resolve", level: "intermediate" },
    ],
    rating: 4.7,
    reviewCount: 52,
    available: true,
    servicesCount: 3,
    completedProjects: 28,
    verified: true,
    phone: "+63 920 456 7890",
    socials: { facebook: "carlos.edits", instagram: "@carlos.motion" },
    createdAt: "2024-07-20T00:00:00Z",
  },
  {
    id: "t5",
    userId: "u5",
    username: "sofia-reyes",
    firstName: "Sofia",
    lastName: "Reyes",
    email: "sofia.reyes@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_sofia.png",
    initials: "SR",
    bio: "Graphic designer with a keen eye for branding and visual identity. I create logos, marketing collaterals, and social media graphics that make brands stand out. Fine Arts major at Bicol University.",
    role: "talent",
    headline: "Graphic Designer & Brand Strategist",
    location: "Legazpi City",
    minRate: 500,
    maxRate: 750,
    skills: [
      { name: "Adobe Illustrator", level: "expert" },
      { name: "Adobe Photoshop", level: "expert" },
      { name: "Branding", level: "expert" },
      { name: "Print Design", level: "intermediate" },
      { name: "Canva", level: "expert" },
    ],
    rating: 4.9,
    reviewCount: 98,
    available: true,
    servicesCount: 4,
    completedProjects: 55,
    verified: false,
    phone: "+63 921 567 8901",
    socials: { facebook: "sofia.designs", instagram: "@sofia.graphix" },
    createdAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "t6",
    userId: "u6",
    username: "miguel-torres",
    firstName: "Miguel",
    lastName: "Torres",
    email: "miguel.torres@bicol-u.edu.ph",
    avatarUrl: "/images/avatar_miguel.png",
    initials: "MT",
    bio: "Professional photographer specializing in portraits, events, and product photography. I capture moments that tell stories. Fine Arts major with focus on Photography at Bicol University.",
    role: "talent",
    headline: "Professional Photographer",
    location: "Daraga",
    minRate: 1000,
    maxRate: 1500,
    skills: [
      { name: "Portrait Photography", level: "expert" },
      { name: "Event Photography", level: "expert" },
      { name: "Product Photography", level: "expert" },
      { name: "Lightroom", level: "expert" },
      { name: "Studio Lighting", level: "intermediate" },
    ],
    rating: 5,
    reviewCount: 76,
    available: true,
    servicesCount: 3,
    completedProjects: 44,
    verified: true,
    phone: "+63 922 678 9012",
    socials: { facebook: "miguel.shots", instagram: "@miguel.captures" },
    createdAt: "2024-04-10T00:00:00Z",
  },
];
